"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%i+3t0^ayj(&vz+cj3q49nie89tzrno(c&rzl5zghpkyop9$!('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_filters',
    'news',
    'sign',
    'protect',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'allauth.socialaccount.providers.google',
    'django_apscheduler',
    'scheduler.apps.SchedulerConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# allauth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # DEV вариант
DEFAULT_FROM_EMAIL = 'no-reply@news-portal.local'

# Admin email settings for error logging
ADMINS = [
    ('Admin', 'admin@news-portal.local'),
]

# PROD пример (замени на реальные значения)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.yourprovider.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = '...'
# EMAIL_HOST_PASSWORD = '...'
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'News Portal <no-reply@yourdomain>'

# Логины по email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # требуем подтверждение

# Куда редиректить
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/news/'

# Кастомная форма регистрации
ACCOUNT_FORMS = {'signup': 'sign.models.CommonSignupForm'}

# Social login settings - direct redirect to providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'yandex': {
        'SCOPE': [
            'login:email',
            'login:info',
        ],
    }
}

# Skip intermediate pages for social logins
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Bypass intermediate pages - go directly to OAuth providers
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_USERNAME_REQUIRED = False

# Cache Configuration
# Используем локальное кэширование в памяти по умолчанию
# Если Redis доступен, можно переключиться на него вручную
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'KEY_PREFIX': 'newsportal',
        'TIMEOUT': 300,  # 5 минут по умолчанию
    }
}

# Если Redis доступен, можно использовать его (раскомментируйте при запущенном Redis):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Используем базу 1 для кэша (0 для Celery)
#         'KEY_PREFIX': 'newsportal',
#         'TIMEOUT': 300,  # 5 минут по умолчанию
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'SOCKET_CONNECT_TIMEOUT': 1,
#             'SOCKET_TIMEOUT': 1,
#             'IGNORE_EXCEPTIONS': True,  # Игнорировать ошибки подключения
#         }
#     }
# }

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # URL для подключения к Redis
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Хранение результатов задач
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Используем тот же часовой пояс, что и Django
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 минут максимум на задачу
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 минут мягкий лимит

CELERY_BEAT_SCHEDULE = {
    'weekly-digest': {
        'task': 'news.tasks.send_weekly_digest',
        'schedule': crontab(hour=8, minute=0, day_of_week=1),  # Каждый понедельник в 8:00
        'options': {
            'expires': 60.0 * 60 * 24,  # Истекает через день
        },
    },
}

# Logging Configuration
import os
import logging

# Создаем директорию для логов, если её нет
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Кастомный форматтер для консоли (меняет формат в зависимости от уровня)
        'console': {
            '()': 'config.logging_filters.ConsoleFormatter',
            'style': '{',
        },
        # Форматтер для general.log: время, уровень, модуль, сообщение
        'general': {
            'format': '{asctime} {levelname} {module} {message}',
            'style': '{',
        },
        # Форматтер для errors.log: время, уровень, сообщение, pathname, exc_info
        'errors': {
            '()': 'config.logging_filters.ErrorsFormatter',
            'format': '{asctime} {levelname} {message} {pathname}',
            'style': '{',
        },
        # Форматтер для security.log: время, уровень, модуль, сообщение
        'security': {
            'format': '{asctime} {levelname} {module} {message}',
            'style': '{',
        },
        # Форматтер для email: время, уровень, сообщение, pathname (без exc_info)
        'email': {
            'format': '{asctime} {levelname} {message} {pathname}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'config.logging_filters.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'config.logging_filters.RequireDebugFalse',
        },
    },
    'handlers': {
        # Консольный обработчик: DEBUG и выше, только при DEBUG=True
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'filters': ['require_debug_true'],
        },
        # Обработчик для general.log: INFO и выше, только при DEBUG=False
        'general_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'general.log',
            'formatter': 'general',
            'filters': ['require_debug_false'],
        },
        # Обработчик для errors.log: ERROR и CRITICAL
        'errors_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'formatter': 'errors',
        },
        # Обработчик для security.log: все уровни из django.security
        'security_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'security.log',
            'formatter': 'security',
        },
        # Email обработчик: ERROR и выше, только при DEBUG=False
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'email',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        # Основной логгер Django
        'django': {
            'handlers': ['console', 'general_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Логгер для запросов
        'django.request': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер для сервера
        'django.server': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер для шаблонов
        'django.template': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер для базы данных
        'django.db.backends': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер для безопасности
        'django.security': {
            'handlers': ['security_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'general_file'],
        'level': 'DEBUG',
    },
}